<?php

return [
    'adminEmail' => 'admin@example.com',
    'th_location' => ['เอกชล1', 'เอกชล2', 'เอกชล1, เอกชล2'],
    'en_location' => ['Aikchol 1', 'Aikchol 2', 'Aikchol 1, Aikchol 2'],
    'th_month' => ["ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค."],
    'en_month' => ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"],
    'th_gender' => ['หญิง', 'ชาย'],
    'en_gender' => ['Female', 'Male'],
    'th_national' => ["อัฟกานิสถาน","แอลเบเนีย","แอลจีเรีย","อเมริกัน","อันดอร์รา","แองโกลา","แอนติกา","อาร์เจนตินา","อาร์เมเนีย","ออสเตรเลีย","ออสเตรีย","อาเซอร์ไบจัน","บาฮามาส","บาห์เรน","บังคลาเทศ","บาร์เบโดส","บอตสวานา","เบลารุส","เบลเยียม","เบลีซ","เบนิน","ภูฏาน","โบลิเวีย","บอสเนีย","บราซิล","อังกฤษ","บรูไน","บัลแกเรีย","พม่า","บุรุนดี","กัมพูชา","แคเมอรูน","แคนาดา","เคปเวอร์","แอฟริกากลาง","ชาด","ชิลี","จีน","โคลอมเบีย","โคโมโรส","คองโก","คอสตาริกา","โครเอเชีย","คิวบา","ไซปรัส","เช็ก","เดนมาร์ก","จิบูตี","โดมินิกัน","ดัตช์","ติมอร์ตะวันออก","เอกวาดอร์","อียิปต์","เอมิเรตส์","ทอเรียลกินี","เอริเทรีย","เอสโตเนีย","เอธิโอเปีย","ฟิจิ","ฟิลิปปินส์","ฟินแลนด์","ฝรั่งเศส","กาบอง","แกมเบีย","จอร์เจีย","เยอรมัน","กานา","กรีก","เกรเนดา","กัวเตมาลา","กินี-Bissauan","กินี","กายอานา","เฮติ","เฮอร์เซโกวีนา","ฮอนดูรัส","ฮังการี","ไอซ์แลนด์","อินเดีย","อินโดนีเซีย","อิหร่าน","อิรัก","ไอริช","อิสราเอล","อิตาลี","ไอวอรี","จาเมกา","ญี่ปุ่น","จอร์แดน","คาซัคสถาน","เคนยา","คูเวต","คีร์กีซ","ลาว","ลัตเวีย","เลบานอน","ไลบีเรีย","ลิเบีย","ลิกเตนสไตน์","ลิทัวเนีย","ลักเซมเบิร์ก","มาซิโดเนีย","มาดากัสการ์","มาลาวี","มาเลเซีย","มัลดีฟส์","มาลี","มอลตา","มาร์แชลล์","ชาว","มอริเชียส","เม็กซิกัน","ไมโครนีเซีย","มอลโดวา","โมนาโค","มองโกเลีย","โมร็อกโก","บอสวานา","โมซัมบิก","นามิเบีย","นาอูรู","เนปาล","นิวซีแลนด์","วานูอาตู","นิคารากัว","ไนเจอร์","เกาหลีเหนือ","ไอร์แลนด์เหนือ","นอร์เวย์","โอมาน","ปากีสถาน","ปาเลา","ปานามา","ปาปัวนิวกีนี","ปารากวัย","เปรู","โปแลนด์","โปรตุเกส","กาตาร์","โรมาเนีย","รัสเซีย","รวันดา","เซนต์ลูเชีย","เอลซัลวาดอร์","ซามัว","ซานมารีโน","เซาตูเม","ซาอุดีอาระเบีย","สก็อต","เซเนกัล","เซอร์เบีย","เซเชลส์","เซียร์ราลีโอน","สิงคโปร์","สโลวาเกีย","สโลวีเนีย","เกาะโซโลมอน","โซมาเลีย","แอฟริกาใต้","เกาหลีใต้","สเปน","ศรีลังกา","ซูดาน","ซูรินาม","สวาซิแลนด์","สวีเดน","สวิส","ซีเรีย","ไต้หวัน","ทาจิกิสถาน","แทนซาเนีย","ไทย","โตโก","ตองกา","ตรินิแดด","ตูนิเซีย","ตุรกี","ตูวาลู","ยูกันดา","ยูเครน","อุรุกวัย","อุซเบกิสถาน","เวเนซุเอลา","เวียดนาม","เวลส์","เยเมน","แซมเบีย","ซิมบับเว"],
    'en_national' => ["Afghan","Albanian","Algerian","American","Andorran","Angolan","Antiguans","Argentinean","Armenian","Australian","Austrian","Azerbaijani","Bahamian","Bahraini","Bangladeshi","Barbadian","Barbudans","Batswana","Belarusian","Belgian","Belizean","Beninese","Bhutanese","Bolivian","Bosnian","Brazilian","British","Bruneian","Bulgarian","Burkinabe","Burmese","Burundian","Cambodian","Cameroonian","Canadian","Cape Verdean","Central African","Chadian","Chilean","Chinese","Colombian","Comoran","Congolese","Costa Rican","Croatian","Cuban","Cypriot","Czech","Danish","Djibouti","Dominican","Dutch","East Timorese","Ecuadorean","Egyptian","Emirian","Equatorial Guinean","Eritrean","Estonian","Ethiopian","Fijian","Filipino","Finnish","French","Gabonese","Gambian","Georgian","German","Ghanaian","Greek","Grenadian","Guatemalan","Guinea-Bissauan","Guinean","Guyanese","Haitian","Herzegovinian","Honduran","Hungarian","Icelander","Indian","Indonesian","Iranian","Iraqi","Irish","Israeli","Italian","Ivorian","Jamaican","Japanese","Jordanian","Kazakhstani","Kenyan","Kittian and Nevisian","Kuwaiti","Kyrgyz","Laotian","Latvian","Lebanese","Liberian","Libyan","Liechtensteiner","Lithuanian","Luxembourger","Macedonian","Malagasy","Malawian","Malaysian","Maldivan","Malian","Maltese","Marshallese","Mauritanian","Mauritian","Mexican","Micronesian","Moldovan","Monacan","Mongolian","Moroccan","Mosotho","Motswana","Mozambican","Namibian","Nauruan","Nepalese","New Zealander","Ni-Vanuatu","Nicaraguan","Nigerien","North Korean","Northern Irish","Norwegian","Omani","Pakistani","Palauan","Panamanian","Papua New Guinean","Paraguayan","Peruvian","Polish","Portuguese","Qatari","Romanian","Russian","Rwandan","Saint Lucian","Salvadoran","Samoan","San Marinese","Sao Tomean","Saudi","Scottish","Senegalese","Serbian","Seychellois","Sierra Leonean","Singaporean","Slovakian","Slovenian","Solomon Islander","Somali","South African","South Korean","Spanish","Sri Lankan","Sudanese","Surinamer","Swazi","Swedish","Swiss","Syrian","Taiwanese","Tajik","Tanzanian","Thai","Togolese","Tongan","Trinidadian or Tobagonian","Tunisian","Turkish","Tuvaluan","Ugandan","Ukrainian","Uruguayan","Uzbekistani","Venezuelan","Vietnamese","Welsh","Yemenite","Zambian","Zimbabwean"],
    'th_province' => ["กรุงเทพมหานคร","กระบี่","กาญจนบุรี","กาฬสินธุ์","กำแพงเพชร","ขอนแก่น","จันทบุรี","ฉะเชิงเทรา","ชัยนาท","ชัยภูมิ","ชุมพร","ชลบุรี","เชียงใหม่","เชียงราย","ตรัง","ตราด","ตาก","นครนายก","นครปฐม","นครพนม","นครราชสีมา","นครศรีธรรมราช","นครสวรรค์","นราธิวาส","น่าน","นนทบุรี","บึงกาฬ","บุรีรัมย์","ประจวบคีรีขันธ์","ปทุมธานี","ปราจีนบุรี","ปัตตานี","พะเยา","พระนครศรีอยุธยา","พังงา","พิจิตร","พิษณุโลก","เพชรบุรี","เพชรบูรณ์","แพร่","พัทลุง","ภูเก็ต","มหาสารคาม","มุกดาหาร","แม่ฮ่องสอน","ยโสธร","ยะลา","ร้อยเอ็ด","ระนอง","ระยอง","ราชบุรี","ลพบุรี","ลำปาง","ลำพูน","เลย","ศรีสะเกษ","สกลนคร","สงขลา","สมุทรสาคร","สมุทรปราการ","สมุทรสงคราม","สระแก้ว","สระบุรี","สิงห์บุรี","สุโขทัย","สุพรรณบุรี","สุราษฎร์ธานี","สุรินทร์","สตูล","หนองคาย","หนองบัวลำภู","อำนาจเจริญ","อุดรธานี","อุตรดิตถ์","อุทัยธานี","อุบลราชธานี","อ่างทอง"],
    'en_province' => ["Amnat Charoen","Ang Thong","Ayutthaya","Bangkok","Bueng Kan","Buri Ram","Chachoengsao","Chai Nat","Chaiyaphum","Chanthaburi","Chiang Mai","Chiang Rai","Chonburi","Chumphon","Kalasin","Kamphaeng Phet","Kanchanaburi","Khon Kaen","Krabi","Lampang","Lamphun","Loei","Lopburi","Mae Hong Son","Maha Sarakham","Mukdahan","Nakhon Nayok","Nakhon Pathom","Nakhon Phanom","Nakhon Ratchasima","Nakhon Sawan","Nakhon Si Thammarat","Nan","Narathiwat","Nong Bua Lam Phu","Nong Khai","Nonthaburi","Pathum Thani","Pattani","Phang Nga","Phatthalung","Phayao","Phetchabun","Phetchaburi","Phichit","Phitsanulok","Phrae","Phuket","Prachin Buri","Prachuap Khiri Khan","Ranong","Ratchaburi","Rayong","Roi Et","Sa Kaeo","Sakon Nakhon","Samut Prakan","Samut Sakhon","Samut Songkhram","Saraburi","Satun","Sing Buri","Sisaket","Songkhla","Sukhothai","Suphan Buri","Surat Thani","Surin","Tak","Trang","Trat","Ubon Ratchathani","Udon Thani","Uthai Thani","Uttaradit","Yala","Yasothon"],
    'toEmail' => 'rattanapong@suffixbyte.com',
    'fromEmail' => 'no-reply@aikchol.com',
];
